"""
kg_global_export.py — Export Neo4j Knowledge Graph to static JS files.

NO API CALLS — reads Neo4j only.

Writes:
  knowledge_graph/
    global_graph_data.js          ← entire corpus graph
    per_pdf/
      {pdf_name}_graph.js         ← one per PDF

Cross-PDF connections:
  If the same entity name appears in multiple PDFs, a CROSS_DOC
  edge is added between them in the global graph — making
  inter-document relationships visible.

Usage:
  python knowledge_graph/kg_global_export.py
  python knowledge_graph/kg_global_export.py --out_dir knowledge_graph/
"""

import argparse
import json
import os
from collections import defaultdict
from pathlib import Path

from dotenv import load_dotenv
from knowledge_graph.kg_utils import Neo4jClient

load_dotenv()

# ── Paths ─────────────────────────────────────────────────────────────────────

BASE_DIR    = Path(__file__).resolve().parent.parent
KG_DIR      = BASE_DIR / "knowledge_graph"
PER_PDF_DIR = KG_DIR / "per_pdf"

# ── Neo4j pull limit (set high — local DB, no cost) ───────────────────────────

NODE_LIMIT = 10_000
EDGE_LIMIT = 20_000


# ── Neo4j data fetchers ───────────────────────────────────────────────────────

def _fetch_all_entities(neo4j: Neo4jClient) -> list[dict]:
    rows = neo4j.run(
        """
        MATCH (e:Entity)
        RETURN e.id AS id,
               e.name AS name,
               e.type AS type,
               e.source_pdf AS source_pdf
        LIMIT $limit
        """,
        {"limit": NODE_LIMIT},
    )
    return [
        {
            "id":         r["id"],
            "name":       r["name"] or "",
            "type":       r["type"] or "concept",
            "source_pdf": r["source_pdf"] or "unknown",
        }
        for r in rows
        if r.get("id")
    ]


def _fetch_all_relations(neo4j: Neo4jClient) -> list[dict]:
    rows = neo4j.run(
        """
        MATCH (a:Entity)-[r]->(b:Entity)
        RETURN a.id AS source,
               b.id AS target,
               type(r) AS relation,
               a.source_pdf AS src_pdf,
               b.source_pdf AS tgt_pdf
        LIMIT $limit
        """,
        {"limit": EDGE_LIMIT},
    )
    return [
        {
            "source":   r["source"],
            "target":   r["target"],
            "relation": r["relation"] or "RELATED_TO",
            "src_pdf":  r["src_pdf"] or "unknown",
            "tgt_pdf":  r["tgt_pdf"] or "unknown",
        }
        for r in rows
        if r.get("source") and r.get("target")
    ]


# ── Cross-PDF connection builder ──────────────────────────────────────────────

def _build_cross_pdf_edges(entities: list[dict]) -> list[dict]:
    """
    Groups entities by normalised name.
    If the same name appears in 2+ PDFs → adds a CROSS_DOC edge
    between those entity IDs in the global graph.
    """
    name_to_entities: dict[str, list[dict]] = defaultdict(list)
    for ent in entities:
        key = ent["name"].strip().lower()
        if key:
            name_to_entities[key].append(ent)

    cross_edges = []
    for name, group in name_to_entities.items():
        pdfs = {e["source_pdf"] for e in group}
        if len(pdfs) < 2:
            continue

        # Connect every pair that comes from different PDFs
        for i in range(len(group)):
            for j in range(i + 1, len(group)):
                a = group[i]
                b = group[j]
                if a["source_pdf"] != b["source_pdf"]:
                    cross_edges.append({
                        "source":   a["id"],
                        "target":   b["id"],
                        "relation": "CROSS_DOC",
                        "src_pdf":  a["source_pdf"],
                        "tgt_pdf":  b["source_pdf"],
                    })

    return cross_edges


# ── JS writer ─────────────────────────────────────────────────────────────────

def _write_js(path: Path, var_name: str, payload: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        f.write(f"// Auto-generated by kg_global_export.py — do not edit manually\n")
        f.write(f"const {var_name} = {json.dumps(payload, indent=2, ensure_ascii=False)};")
    print(f"  Written → {path}  "
          f"({len(payload['nodes'])} nodes, {len(payload['edges'])} edges)")


# ── Global graph builder ──────────────────────────────────────────────────────

def _build_global_graph(
    entities: list[dict],
    relations: list[dict],
) -> dict:
    cross_edges = _build_cross_pdf_edges(entities)

    nodes = [
        {
            "id":         e["id"],
            "label":      e["name"],
            "type":       e["type"],
            "source_pdf": e["source_pdf"],
            "group":      e["source_pdf"],   # for colour-coding by PDF
        }
        for e in entities
    ]

    edges = [
        {
            "source":   r["source"],
            "target":   r["target"],
            "relation": r["relation"],
            "src_pdf":  r["src_pdf"],
            "tgt_pdf":  r["tgt_pdf"],
            "cross_doc": False,
        }
        for r in relations
    ]

    # Add cross-PDF edges
    for ce in cross_edges:
        edges.append({
            "source":    ce["source"],
            "target":    ce["target"],
            "relation":  "CROSS_DOC",
            "src_pdf":   ce["src_pdf"],
            "tgt_pdf":   ce["tgt_pdf"],
            "cross_doc": True,
        })

    # Collect all unique PDFs for metadata
    all_pdfs = sorted({e["source_pdf"] for e in entities})

    return {
        "graph_type":   "global",
        "pdf_count":    len(all_pdfs),
        "pdfs":         all_pdfs,
        "node_count":   len(nodes),
        "edge_count":   len(edges),
        "cross_doc_edge_count": len(cross_edges),
        "nodes":        nodes,
        "edges":        edges,
    }


# ── Per-PDF graph builder ─────────────────────────────────────────────────────

def _build_per_pdf_graph(
    pdf_name: str,
    entities: list[dict],
    relations: list[dict],
) -> dict:
    # Filter to this PDF only
    pdf_entities = [e for e in entities if e["source_pdf"] == pdf_name]
    pdf_ids      = {e["id"] for e in pdf_entities}

    pdf_relations = [
        r for r in relations
        if r["source"] in pdf_ids and r["target"] in pdf_ids
    ]

    nodes = [
        {
            "id":     e["id"],
            "label":  e["name"],
            "type":   e["type"],
            "group":  e["type"],   # colour by entity type within PDF
        }
        for e in pdf_entities
    ]

    edges = [
        {
            "source":   r["source"],
            "target":   r["target"],
            "relation": r["relation"],
        }
        for r in pdf_relations
    ]

    return {
        "graph_type": "per_pdf",
        "pdf_name":   pdf_name,
        "node_count": len(nodes),
        "edge_count": len(edges),
        "nodes":      nodes,
        "edges":      edges,
    }


# ── Main export ───────────────────────────────────────────────────────────────

def export(out_dir: Path = KG_DIR) -> None:
    print(f"\n{'='*55}")
    print("KG GLOBAL EXPORT  —  Neo4j → JS files")
    print(f"{'='*55}")
    print("No API calls — reading Neo4j only\n")

    with Neo4jClient() as neo4j:
        print("Fetching entities ...")
        entities  = _fetch_all_entities(neo4j)
        print(f"  {len(entities)} entities loaded")

        print("Fetching relations ...")
        relations = _fetch_all_relations(neo4j)
        print(f"  {len(relations)} relations loaded")

    if not entities:
        print("\n[Export] Neo4j graph is empty.")
        print("Run kg_builder.py first.")
        return

    # ── Global graph ──────────────────────────────────────────────────────────
    print("\nBuilding global graph ...")
    global_payload = _build_global_graph(entities, relations)
    _write_js(
        out_dir / "global_graph_data.js",
        "GLOBAL_GRAPH_DATA",
        global_payload,
    )
    print(
        f"  Cross-PDF connections found : "
        f"{global_payload['cross_doc_edge_count']}"
    )

    # ── Per-PDF graphs ────────────────────────────────────────────────────────
    all_pdfs = sorted({e["source_pdf"] for e in entities})
    print(f"\nBuilding per-PDF graphs ({len(all_pdfs)} PDFs) ...")

    per_pdf_index = []   # index file so viewer knows what's available

    for pdf_name in all_pdfs:
        pdf_payload = _build_per_pdf_graph(pdf_name, entities, relations)
        safe_name   = pdf_name.replace("/", "_").replace("\\", "_")
        _write_js(
            out_dir / "per_pdf" / f"{safe_name}_graph.js",
            "PDF_GRAPH_DATA",
            pdf_payload,
        )
        per_pdf_index.append({
            "pdf_name":   pdf_name,
            "js_file":    f"per_pdf/{safe_name}_graph.js",
            "node_count": pdf_payload["node_count"],
            "edge_count": pdf_payload["edge_count"],
        })

    # ── Write index so viewer can populate PDF dropdown ───────────────────────
    index_path = out_dir / "pdf_graph_index.js"
    with index_path.open("w", encoding="utf-8") as f:
        f.write("// Auto-generated — list of available per-PDF graphs\n")
        f.write(f"const PDF_GRAPH_INDEX = {json.dumps(per_pdf_index, indent=2)};")
    print(f"\n  Index written → {index_path}")

    # ── Summary ───────────────────────────────────────────────────────────────
    print(f"\n{'='*55}")
    print("Export complete.")
    print(f"  Global graph : {global_payload['node_count']} nodes | "
          f"{global_payload['edge_count']} edges")
    print(f"  PDFs exported: {len(all_pdfs)}")
    print(f"  Cross-PDF    : {global_payload['cross_doc_edge_count']} connections")
    print(f"\nFiles written to: {out_dir}")
    print(f"{'='*55}")
    print("\nNext: open graph_viewer.html in browser")


# ── Entry point ───────────────────────────────────────────────────────────────

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Export Neo4j KG to static JS files for graph_viewer.html",
        epilog="Example: python knowledge_graph/kg_global_export.py",
    )
    parser.add_argument(
        "--out_dir",
        type=str,
        default=str(KG_DIR),
        help=f"Output directory (default: {KG_DIR})",
    )
    args = parser.parse_args()
    export(out_dir=Path(args.out_dir))